version: '3.1'
services:
  app:
    container_name: Library_MANAGEMENT_SYSTEM
    image: spring_boot
    build: ./
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL= jdbc:postgresql://db:5432/postgres
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=shivam
      - SPRING_JPA_HIBERNATE_DDL_AUTO=none

  db:
    image: 'postgres:13.3-alpine'
    container_name: db
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_PASSWORD=shivam
      - POSTGRES_USER=postgres